export default {
    light: {
        primaryColor: "#f1356d",
        primaryColorLight: "#e4bdc9",
        primarySecondColor: "#F57198",
        inputPlaceholderColor: "#000",
        inputTextColor: "#000",
        backGround: "#C9C9C9",
        backGroundDarker: "#8C8C8C",
        blogItemBackground: "#fff",
        accentColor: "#FFC107",
        primary: "#2BA3F8",
        success: "#33FF99",
        danger: "#F34E41",
        info: "#80C3F3",
    },
    dark: {
        primaryColor: "#424F6D",
        primaryColorLight: "#a0a7b6",
        primarySecondColor: "#67728a",
        inputPlaceholderColor: "#c6cad3",
        inputTextColor: "#fff",
        backGround: "#67728a",
        backGroundDarker: "#8C8C8C",
        blogItemBackground: "#c6cad3",
        accentColor: "#FFC107",
        primary: "#2BA3F8",
        success: "#33FF99",
        danger: "#F34E41",
        info: "#80C3F3",
    },
};
